import * as fs from 'fs';
import * as path from 'path';
import type { ProjectData, WeatherData } from '@hypernovum/core';
import {
  buildClaudeHookJson,
  buildPingExample,
  buildStopExample,
  type HeartbeatPaths,
} from './heartbeatDocs';

/**
 * Write .hypernovum/SETUP.md into a project directory before launching an agent.
 * Gives the agent immediate context about HYPERNOVUM and how to work with project data.
 */
export function generateAgentContext(
  projectDir: string,
  vaultPath: string,
  opts?: {
    project?: ProjectData;
    weather?: WeatherData | null;
    memoryContextPath?: string | null;
    /** Resolved heartbeat script/vault paths; null when the script isn't installed. */
    heartbeat?: HeartbeatPaths | null;
  },
): void {
  try {
    const hvDir = path.join(projectDir, '.hypernovum');
    fs.mkdirSync(hvDir, { recursive: true });

    // Ensure .gitignore so nothing in .hypernovum/ gets committed
    const gitignorePath = path.join(hvDir, '.gitignore');
    if (!fs.existsSync(gitignorePath)) {
      fs.writeFileSync(gitignorePath, '*\n');
    }

    const vaultAgentsPath = path.join(vaultPath, 'AGENTS.md');
    const vaultAgentsNote = fs.existsSync(vaultAgentsPath)
      ? `Vault-level agent instructions live at \`${vaultAgentsPath.replace(/\\/g, '/')}\` — read that file first. It contains the project frontmatter schema and a live inventory of every project in this second brain.`
      : 'No vault-level AGENTS.md was found. The user can generate one in Obsidian via the command palette: "Prepare vault for AI agents".';

    const projectName = opts?.project?.title || path.basename(projectDir);
    const heartbeatSection = buildHeartbeatSection(opts?.heartbeat ?? null, projectName);

    const setupMd = `# HYPERNOVUM — Setup Context

> Auto-generated by the HYPERNOVUM Obsidian plugin on ${new Date().toISOString().slice(0, 19).replace('T', ' ')}.
> This file is gitignored and regenerated on every agent launch.

## What is HYPERNOVUM?

HYPERNOVUM is a 3D "code city" that visualizes projects as buildings in a cyberpunk cityscape. Each project is a building — status maps to color, priority to height, category to district. It runs as an Obsidian plugin.

## This Project

- **Project title:** ${opts?.project?.title || path.basename(projectDir)}
- **Project directory:** \`${projectDir.replace(/\\/g, '/')}\`
- **Obsidian vault:** \`${vaultPath.replace(/\\/g, '/')}\`
- **Project note:** ${opts?.project?.path ? `\`${opts.project.path}\`` : '_Unknown_'}
- **Status:** ${opts?.project?.status || 'unknown'}
- **Priority:** ${opts?.project?.priority || 'unknown'}
- **Category:** ${opts?.project?.category || 'unknown'}

## Current Signals

- **Active branch:** ${opts?.weather?.activeBranch || 'unknown'}
- **Last commit:** ${opts?.weather?.lastCommitDate ? new Date(opts.weather.lastCommitDate).toISOString() : 'unknown'}
- **Commits in last 7 days:** ${opts?.weather?.commitsLast7d ?? 'unknown'}
- **Commits in last 30 days:** ${opts?.weather?.commitsLast30d ?? 'unknown'}
- **Uncommitted changes:** ${opts?.weather ? (opts.weather.hasUncommittedChanges ? 'yes' : 'no') : 'unknown'}
- **Memory context:** ${opts?.memoryContextPath ? `available at \`${opts.memoryContextPath.replace(/\\/g, '/')}\`` : 'none detected'}

## Vault-Level Instructions

${vaultAgentsNote}

## How Projects Are Defined

Projects are Obsidian notes with YAML frontmatter. The plugin scans for notes tagged \`project\` (or with \`type: project\`) and renders them as buildings.

### Frontmatter Schema

\`\`\`yaml
---
tags: [project]
title: "My Project"
status: active          # active | blocked | paused | complete
priority: high          # critical | high | medium | low
category: web-apps      # used for district grouping
stack: [TypeScript, React, Vite]
health: 85              # 0-100 health score
projectDir: "${projectDir.replace(/\\/g, '/')}"
---
\`\`\`

### Status Values
- **active** — currently being worked on (cyan/green buildings)
- **blocked** — waiting on something (red buildings)
- **paused** — on hold (amber buildings)
- **complete** — finished (purple buildings)

### Priority → Building Height
- **critical** — tallest buildings
- **high** — tall buildings
- **medium** — medium buildings
- **low** — short buildings

${heartbeatSection}

---
Generated by the free [Hypernovum](https://github.com/Pardesco/hypernovum) Obsidian plugin. A standalone desktop app with persistent agent memory, an MCP server, and worktree isolation is available as [HYPERNOVUM Pro](https://studio.pardesco.com/hypernovum).
`;

    fs.writeFileSync(path.join(hvDir, 'SETUP.md'), setupMd, 'utf8');
  } catch (err) {
    console.error('[Hypernovum] Failed to generate agent context:', err);
  }
}

/**
 * Heartbeat instructions for the per-project SETUP.md, using the absolute path of
 * the script Hypernovum installed into the vault. Pre-0.4.1 this hardcoded
 * `<vault>/scripts/heartbeat.js` — a repo path absent from every real install, so
 * every agent that followed these instructions failed silently.
 */
function buildHeartbeatSection(heartbeat: HeartbeatPaths | null, projectName: string): string {
  if (!heartbeat) {
    return `## Activity Monitoring (Heartbeat v2)

The heartbeat script is not installed in this vault yet, so agent presence can't
be reported. Ask the user to run the Obsidian command **"Install agent heartbeat
hooks"** — it installs the script and prints ready-to-paste hook JSON.`;
  }

  return `## Activity Monitoring (Heartbeat v2)

You can make your session visible in the city as a named, stateful agent orb by
emitting v2 heartbeats. Each session writes its own snapshot file — any number
of agents run concurrently without clobbering each other. Every path below is
already resolved for this machine; run the commands as-is.

Per-ping (call whenever you use a tool or change state):

\`\`\`bash
${buildPingExample(heartbeat, projectName)}
\`\`\`

On finish:

\`\`\`bash
${buildStopExample(heartbeat)}
\`\`\`

- **Reuse one \`--id\` for every ping in a session** so they all update the same orb.
  Pick any stable string. (From a Claude Code hook, pass \`--hook\` instead and the
  script reads the real \`session_id\` from the hook's stdin JSON — there is no
  \`$CLAUDE_SESSION_ID\` environment variable.)
- **\`--state\`** is one of: starting, planning, reading, editing, running,
  testing, reviewing, waiting, blocked, complete, failed. If omitted, the plugin
  infers a state from \`--tool\`/\`--action\`.
- **\`--file\`** (project-relative preferred) lets the city detect when two agents
  touch the same file and raise a conflict.
- Snapshots are written to \`<vault>/.hypernovum/agents/<sessionId>.json\`. The
  plugin polls that directory and renders one orb per session, colored by state,
  with an identity tooltip.

### Claude Code hooks (\`~/.claude/settings.json\`)

\`\`\`json
${buildClaudeHookJson(heartbeat)}
\`\`\``;
}

// Note: Agent context is provided via .hypernovum/SETUP.md written by generateAgentContext().
// No command enrichment needed — agents discover the file naturally.
