import * as fs from 'fs';
import * as path from 'path';
import type { ProjectData, WeatherData } from '@hypernovum/core';

/**
 * Write .hypernovum/SETUP.md into a project directory before launching an agent.
 * Gives the agent immediate context about HYPERNOVUM and how to work with project data.
 */
export function generateAgentContext(
  projectDir: string,
  vaultPath: string,
  opts?: { project?: ProjectData; weather?: WeatherData | null; memoryContextPath?: string | null },
): void {
  try {
    const hvDir = path.join(projectDir, '.hypernovum');
    fs.mkdirSync(hvDir, { recursive: true });

    // Ensure .gitignore so nothing in .hypernovum/ gets committed
    const gitignorePath = path.join(hvDir, '.gitignore');
    if (!fs.existsSync(gitignorePath)) {
      fs.writeFileSync(gitignorePath, '*\n');
    }

    const vaultAgentsPath = path.join(vaultPath, 'AGENTS.md');
    const vaultAgentsNote = fs.existsSync(vaultAgentsPath)
      ? `Vault-level agent instructions live at \`${vaultAgentsPath.replace(/\\/g, '/')}\` — read that file first. It contains the project frontmatter schema and a live inventory of every project in this second brain.`
      : 'No vault-level AGENTS.md was found. The user can generate one in Obsidian via the command palette: "Prepare vault for AI agents".';

    const setupMd = `# HYPERNOVUM — Setup Context

> Auto-generated by the HYPERNOVUM Obsidian plugin on ${new Date().toISOString().slice(0, 19).replace('T', ' ')}.
> This file is gitignored and regenerated on every agent launch.

## What is HYPERNOVUM?

HYPERNOVUM is a 3D "code city" that visualizes projects as buildings in a cyberpunk cityscape. Each project is a building — status maps to color, priority to height, category to district. It runs as an Obsidian plugin.

## This Project

- **Project title:** ${opts?.project?.title || path.basename(projectDir)}
- **Project directory:** \`${projectDir.replace(/\\/g, '/')}\`
- **Obsidian vault:** \`${vaultPath.replace(/\\/g, '/')}\`
- **Project note:** ${opts?.project?.path ? `\`${opts.project.path}\`` : '_Unknown_'}
- **Status:** ${opts?.project?.status || 'unknown'}
- **Priority:** ${opts?.project?.priority || 'unknown'}
- **Category:** ${opts?.project?.category || 'unknown'}

## Current Signals

- **Active branch:** ${opts?.weather?.activeBranch || 'unknown'}
- **Last commit:** ${opts?.weather?.lastCommitDate ? new Date(opts.weather.lastCommitDate).toISOString() : 'unknown'}
- **Commits in last 7 days:** ${opts?.weather?.commitsLast7d ?? 'unknown'}
- **Commits in last 30 days:** ${opts?.weather?.commitsLast30d ?? 'unknown'}
- **Uncommitted changes:** ${opts?.weather ? (opts.weather.hasUncommittedChanges ? 'yes' : 'no') : 'unknown'}
- **Memory context:** ${opts?.memoryContextPath ? `available at \`${opts.memoryContextPath.replace(/\\/g, '/')}\`` : 'none detected'}

## Vault-Level Instructions

${vaultAgentsNote}

## How Projects Are Defined

Projects are Obsidian notes with YAML frontmatter. The plugin scans for notes tagged \`project\` (or with \`type: project\`) and renders them as buildings.

### Frontmatter Schema

\`\`\`yaml
---
tags: [project]
title: "My Project"
status: active          # active | blocked | paused | complete
priority: high          # critical | high | medium | low
category: web-apps      # used for district grouping
stack: [TypeScript, React, Vite]
health: 85              # 0-100 health score
projectDir: "${projectDir.replace(/\\/g, '/')}"
---
\`\`\`

### Status Values
- **active** — currently being worked on (cyan/green buildings)
- **blocked** — waiting on something (red buildings)
- **paused** — on hold (amber buildings)
- **complete** — finished (purple buildings)

### Priority → Building Height
- **critical** — tallest buildings
- **high** — tall buildings
- **medium** — medium buildings
- **low** — short buildings

## Activity Monitoring

If you're Claude Code, you can make your activity visible in the city by using the heartbeat script:

\`\`\`bash
node "${vaultPath.replace(/\\/g, '/')}/scripts/heartbeat.js" --vault="${vaultPath.replace(/\\/g, '/')}" --project="PROJECT_NAME" --action="editing"
\`\`\`

This writes \`.hypernovum-status.json\` to the vault root. The plugin polls it and triggers streaming animations on the corresponding building.

---
Generated by the free [Hypernovum](https://github.com/Pardesco/hypernovum) Obsidian plugin. A standalone desktop app with persistent agent memory, an MCP server, and worktree isolation is available as [HYPERNOVUM Pro](https://studio.pardesco.com/hypernovum).
`;

    fs.writeFileSync(path.join(hvDir, 'SETUP.md'), setupMd, 'utf8');
  } catch (err) {
    console.error('[Hypernovum] Failed to generate agent context:', err);
  }
}

// Note: Agent context is provided via .hypernovum/SETUP.md written by generateAgentContext().
// No command enrichment needed — agents discover the file naturally.
