import { normalizePath, TFile, type App } from 'obsidian';
import type { ProjectData } from '@hypernovum/core';
import type { AgentSkill } from './SkillsScanner';
import { buildPingExample, buildStopExample, type HeartbeatPaths } from './heartbeatDocs';

const START_MARKER = '<!-- hypernovum:start -->';
const END_MARKER = '<!-- hypernovum:end -->';
const AGENTS_FILE = 'AGENTS.md';
const MAX_INVENTORY_ROWS = 50;

export interface PrepareVaultResult {
  created: boolean;   // true = AGENTS.md was created, false = existing file updated
  projectCount: number;
}

/**
 * Write (or update) a Hypernovum section in the vault-root AGENTS.md so any
 * CLI agent launched in the vault understands the project city: what it is,
 * the frontmatter schema, the current project inventory, and how to make its
 * activity visible in the 3D view.
 *
 * The section lives between marker comments. An existing AGENTS.md is never
 * clobbered — only the marked section is replaced (or appended if absent).
 */
export async function prepareVaultForAgents(
  app: App,
  projects: ProjectData[],
  skills: AgentSkill[] = [],
  heartbeat: HeartbeatPaths | null = null,
): Promise<PrepareVaultResult> {
  const section = buildSection(projects, skills, heartbeat);
  const filePath = normalizePath(AGENTS_FILE);

  // Vault API, not the adapter: AGENTS.md is user-visible content, so it needs to
  // land in Obsidian's file index and fire the usual create/modify events.
  const existing = app.vault.getAbstractFileByPath(filePath);

  if (!(existing instanceof TFile)) {
    await app.vault.create(
      filePath,
      `# AGENTS.md\n\nInstructions for AI coding agents working in this Obsidian vault.\n\n${section}\n`,
    );
    return { created: true, projectCount: projects.length };
  }

  await app.vault.process(existing, (current) => {
    const startIdx = current.indexOf(START_MARKER);
    const endIdx = current.indexOf(END_MARKER);

    if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
      // Replace the existing marked section in place
      return current.slice(0, startIdx) + section + current.slice(endIdx + END_MARKER.length);
    }
    // Append the section, preserving everything the user already wrote
    return `${current.replace(/\s*$/, '')}\n\n${section}\n`;
  });

  return { created: false, projectCount: projects.length };
}

function buildSection(projects: ProjectData[], skills: AgentSkill[], heartbeat: HeartbeatPaths | null): string {
  const timestamp = new Date().toISOString().slice(0, 19).replace('T', ' ');
  const inventory = buildInventory(projects);
  const questBoard = buildQuestBoard(projects);
  const skillsRoster = buildSkillsRoster(skills);
  const heartbeatSection = buildHeartbeatSection(heartbeat);

  return `${START_MARKER}
## Hypernovum project city

> Auto-generated by the Hypernovum Obsidian plugin on ${timestamp}.
> Regenerate via the command palette: "Prepare vault for AI agents".
> Everything between the hypernovum markers is overwritten on regeneration — put your own instructions outside this block.

This vault is a "second brain" rendered as a 3D code city by the [Hypernovum](https://github.com/Pardesco/hypernovum) plugin. Each project note becomes a building: status maps to color, priority to height, category to district. You (the agent) can add, update, and maintain projects by editing plain markdown notes — the city re-renders automatically.

### How to add or update a project

Create or edit a note anywhere in the vault with this frontmatter:

\`\`\`yaml
---
tags: [project]
title: "My Project"
status: active          # active | blocked | paused | complete
priority: high          # critical | high | medium | low
category: web-apps      # groups buildings into districts
stack: [TypeScript, React]
health: 85              # optional 0-100 health score
projectDir: "C:/path/to/repo"   # optional absolute or vault-relative path
questions:              # optional open research questions — rendered as quest markers
  - "Which vector DB fits this workload?"
---
\`\`\`

- **status** → building color: active = green, blocked = red, paused = blue, complete = purple.
- **priority** → building height: critical is tallest, low is shortest.
- **category** → free-form; identical values share a city district.
- **projectDir** → lets Hypernovum read Git activity and launch agents in the right folder.

Keep frontmatter values current as work progresses (e.g. flip \`status\` to \`blocked\` when a project stalls) — the city is only as truthful as the notes.

${inventory}

${questBoard}

${skillsRoster}

### Per-project agent context

When Hypernovum launches an agent for a project it writes \`.hypernovum/SETUP.md\` (gitignored) into the project directory with fresh metadata and Git signals — read it first if present. If a project directory contains \`.hypernovum/MEMORY_CONTEXT.md\`, treat it as persistent memory: read it before starting and consider updating it when you finish significant work.

${heartbeatSection}
${END_MARKER}`;
}

/**
 * The heartbeat instructions, pointing at the script Hypernovum installed into
 * this vault. Paths are fully resolved — earlier versions emitted
 * `<vault-root>/scripts/heartbeat.js`, a repo path that does not exist in an
 * installed plugin, so no agent could ever ping successfully.
 */
function buildHeartbeatSection(heartbeat: HeartbeatPaths | null): string {
  if (!heartbeat) {
    return `### Make your activity visible (Heartbeat v2)

The heartbeat script is not installed in this vault yet. In Obsidian, run the
command palette action **"Install agent heartbeat hooks"** — it writes the script
to \`.hypernovum/heartbeat.js\` and prints ready-to-paste hook JSON. Re-run
**"Prepare vault for AI agents"** afterwards and this section will contain the
exact commands for this machine.`;
  }

  return `### Make your activity visible (Heartbeat v2)

While working, emit a v2 heartbeat so your session appears as a named, stateful orb. Each session owns its own snapshot file, so concurrent agents never clobber each other. These commands are already resolved for this vault — run them as-is:

\`\`\`bash
${buildPingExample(heartbeat, 'My Project')}

# when done:
${buildStopExample(heartbeat)}
\`\`\`

- Reuse one \`--id\` for every ping in a session so they all update the same orb — pick any stable string. (From a Claude Code hook, pass \`--hook\` instead: the script then reads the real \`session_id\` from the hook's stdin JSON. There is no \`$CLAUDE_SESSION_ID\` environment variable.)
- \`--state\`: starting | planning | reading | editing | running | testing | reviewing | waiting | blocked | complete | failed (inferred from \`--tool\`/\`--action\` if omitted).
- \`--file\` (project-relative) enables same-file conflict detection between agents.
- \`--project\` should match the project note's title.
- Snapshots land in \`<vault>/.hypernovum/agents/<sessionId>.json\`; the plugin treats pings older than 10s as idle, then stale.

The script itself lives at \`${heartbeat.scriptPath}\` — Hypernovum installs and updates it, so don't edit it by hand.

A legacy single-file \`.hypernovum-status.json\` is still read for one release (renders as an anonymous agent), but v2 gives you identity, state, and conflict detection. When Hypernovum launches an agent it writes the full per-project invocation into that project's \`.hypernovum/SETUP.md\`.`;
}

function buildInventory(projects: ProjectData[]): string {
  if (projects.length === 0) {
    return `### Current projects (0)

No project notes exist yet — this vault is waiting to be populated. Use the schema above to create them.`;
  }

  const shown = projects.slice(0, MAX_INVENTORY_ROWS);
  const rows = shown.map((p) => {
    const dir = p.projectDir ? `\`${escapeCell(p.projectDir.replace(/\\/g, '/'))}\`` : '—';
    return `| ${escapeCell(p.title)} | ${escapeCell(p.status)} | ${escapeCell(p.priority)} | ${escapeCell(p.category)} | \`${escapeCell(p.path)}\` | ${dir} |`;
  });

  const truncated = projects.length > shown.length
    ? `\n\n_…and ${projects.length - shown.length} more. Search the vault for \`tags: [project]\` for the full set._`
    : '';

  return `### Current projects (${projects.length})

| Title | Status | Priority | Category | Note | Directory |
|-------|--------|----------|----------|------|-----------|
${rows.join('\n')}${truncated}`;
}

function buildQuestBoard(projects: ProjectData[]): string {
  const withQuests = projects.filter((p) => p.questions && p.questions.length > 0);
  const total = withQuests.reduce((sum, p) => sum + (p.questions?.length ?? 0), 0);

  if (total === 0) {
    return `### Research quest board (0 open)

No open quests. Users post quests by adding a \`questions:\` list to a project note's frontmatter — check here on future runs.`;
  }

  const rows = withQuests.flatMap((p) =>
    (p.questions ?? []).map((q) => `- **${p.title}** (\`${p.path}\`): ${q.replace(/\r?\n/g, ' ')}`)
  );

  return `### Research quest board (${total} open)

Open questions posted by the user. If your current task touches one of these projects — or you were asked to work the quest board — pick a quest up:

${rows.join('\n')}

When you resolve a quest: write the answer (with sources) into the project note body, then move the entry from the note's \`questions:\` list to an \`answered:\` list in the same frontmatter. The city fires a resolution shockwave and clears the quest marker automatically.`;
}

function buildSkillsRoster(skills: AgentSkill[]): string {
  if (skills.length === 0) {
    return `### Available skills

No SKILL.md files found in \`.claude/skills/\` (vault) or \`~/.claude/skills/\` (global).`;
  }

  const rows = skills.map((s) =>
    `- **${s.name}** (${s.scope}) — ${s.description || 'no description'}\n  \`${s.path.replace(/\\/g, '/')}\``
  );

  return `### Available skills

Reusable skills installed on this machine. Read a skill's SKILL.md before using it:

${rows.join('\n')}`;
}

function escapeCell(value: string): string {
  return (value ?? '').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}
